quarkus.rest-client.speech-generation-client.url=http://coqui-be:8000
quarkus.rest-client.transcription-client.url=http://whisper-be:8000
quarkus.rest-client.field-response-client.url=http://backend:5200/api/field-responses
quarkus.rest-client.group-client.url=http://backend:5200/api/groups
quarkus.rest-client.option-response-client.url=http://backend:5200/api/option-responses

#Use for deployment: http://asterisk:8088
fabia.ari.url=http://asterisk:8088
fabia.ari.name=my-ari-app
fabia.ari.user=ariuser
fabia.ari.pass=aripass

quarkus.package.jar.type=uber-jar

#quarkus.log.category."ch.loway.oss.ari4java".level=DEBUG
#quarkus.log.category."ch.loway.oss.ari4java.generated.AriWSHelper".level=DEBUG
#quarkus.log.category."org.asynchttpclient".level=DEBUG
quarkus.log.level=DEBUG