quarkus.http.host-enabled=false

quarkus.rest-client.speech-generation-client.url=http://coqui-be:8000
quarkus.rest-client.transcription-client.url=http://whisper-be:8000
quarkus.rest-client.field-response-client.url=http://backend:5200/api/field-responses
quarkus.rest-client.group-client.url=http://backend:5200/api/groups
quarkus.rest-client.option-response-client.url=http://backend:5200/api/option-responses

fabia.ari.url=http://asterisk:8088/
fabia.ari.name=my-ari-app
fabia.ari.user=ariUser
fabia.ari.pass=ariPass