[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_signaling_address=169.254.83.107;ADD_LOCAL_IP_ADDRESS
external_media_address=169.254.83.107;ADD_LOCAL_IP_ADDRESS

[1000]
type=endpoint
context=default
disallow=all
allow=ulaw
auth=1000-auth
aors=1000
direct_media=no

[1000-auth]
type=auth
auth_type=userpass
username=1000
password=1234

[1000]
type=aor
max_contacts=1
remove_existing=yes