services:
  asterisk:
    build:
      context: ./Asterisk
      dockerfile: Dockerfile
    ports:
      - "5060:5060/udp"
      - "8088:8088"
      - "10000-10100:10000-10100/udp"
    volumes:
      - ./ARIApp/audio:/var/lib/asterisk/sounds/custom
